// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/2LAonX011yB
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Rubik } from 'next/font/google'
// import { IBM_Plex_Sans } from 'next/font/google'

// rubik({
//   subsets: ['latin'],
//   display: 'swap',
// })

// ibm_plex_sans({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import Link from "next/link"
// import { Label } from "@/components/ui/label"
// import { Input } from "@/components/ui/input"
// import { Textarea } from "@/components/ui/textarea"
// import { Button } from "@/components/ui/button"

// export function kedua() {
//   return (
//     <div className="flex flex-col min-h-[100dvh]">
//       <header className="px-4 lg:px-6 h-14 flex items-center">
//         <Link href="#" className="flex items-center justify-center" prefetch={false}>
//           <MountainIcon className="h-6 w-6" />
//           <span className="sr-only">John Doe's Portfolio</span>
//         </Link>
//         <nav className="ml-auto flex gap-4 sm:gap-6">
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             About
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Skills
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Projects
//           </Link>
//           <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
//             Contact
//           </Link>
//         </nav>
//       </header>
//       <main className="flex-1">
//         <section id="hero" className="w-full py-12 md:py-24 lg:py-32">
//           <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
//             <div className="flex flex-col items-center justify-center space-y-4 text-center lg:items-start lg:text-left">
//               <div className="space-y-2">
//                 <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">John Doe</h1>
//                 <p className="max-w-[600px] text-muted-foreground md:text-xl">
//                   Im a full-stack developer with a passion for creating beautiful and functional web applications.
//                 </p>
//               </div>
//             </div>
//             <div className="flex justify-center">
//               <img
//                 src="/placeholder.svg"
//                 width="400"
//                 height="400"
//                 alt="John Doe"
//                 className="rounded-full w-[300px] h-[300px] object-cover"
//               />
//             </div>
//           </div>
//         </section>
//         <section id="about" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
//           <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
//             <div className="space-y-4">
//               <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">About Me</div>
//               <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Background</h2>
//               <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
//                 I have over 5 years of experience in web development, working with a variety of technologies and
//                 frameworks. I'm passionate about creating user-friendly and visually appealing applications that solve
//                 real-world problems.
//               </p>
//             </div>
//             <div className="space-y-4">
//               <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Skills</div>
//               <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">What I Can Do</h2>
//               <div className="grid grid-cols-2 gap-4">
//                 <div className="bg-background rounded-lg p-4 shadow-sm">
//                   <h3 className="text-lg font-semibold">Front-end</h3>
//                   <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
//                     <li>React</li>
//                     <li>Vue.js</li>
//                     <li>HTML/CSS</li>
//                     <li>JavaScript</li>
//                   </ul>
//                 </div>
//                 <div className="bg-background rounded-lg p-4 shadow-sm">
//                   <h3 className="text-lg font-semibold">Back-end</h3>
//                   <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
//                     <li>Node.js</li>
//                     <li>Express</li>
//                     <li>Python</li>
//                     <li>Django</li>
//                   </ul>
//                 </div>
//                 <div className="bg-background rounded-lg p-4 shadow-sm">
//                   <h3 className="text-lg font-semibold">Databases</h3>
//                   <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
//                     <li>MongoDB</li>
//                     <li>PostgreSQL</li>
//                     <li>MySQL</li>
//                   </ul>
//                 </div>
//                 <div className="bg-background rounded-lg p-4 shadow-sm">
//                   <h3 className="text-lg font-semibold">Tools</h3>
//                   <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
//                     <li>Git</li>
//                     <li>Docker</li>
//                     <li>AWS</li>
//                     <li>Figma</li>
//                   </ul>
//                 </div>
//               </div>
//             </div>
//           </div>
//         </section>
//         <section id="projects" className="w-full py-12 md:py-24 lg:py-32">
//           <div className="container space-y-12 px-4 md:px-6">
//             <div className="flex flex-col items-center justify-center space-y-4 text-center">
//               <div className="space-y-2">
//                 <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Featured Projects</div>
//                 <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">My Work</h2>
//                 <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
//                   Check out some of the projects I've worked on.
//                 </p>
//               </div>
//             </div>
//             <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
//               <div className="bg-background rounded-lg shadow-sm overflow-hidden">
//                 <img
//                   src="/placeholder.svg"
//                   width="550"
//                   height="310"
//                   alt="Project 1"
//                   className="w-full h-48 object-cover"
//                 />
//                 <div className="p-4 space-y-2">
//                   <h3 className="text-lg font-semibold">Project 1</h3>
//                   <p className="text-muted-foreground">
//                     A web application that helps users manage their tasks and projects.
//                   </p>
//                 </div>
//               </div>
//               <div className="bg-background rounded-lg shadow-sm overflow-hidden">
//                 <img
//                   src="/placeholder.svg"
//                   width="550"
//                   height="310"
//                   alt="Project 2"
//                   className="w-full h-48 object-cover"
//                 />
//                 <div className="p-4 space-y-2">
//                   <h3 className="text-lg font-semibold">Project 2</h3>
//                   <p className="text-muted-foreground">A mobile app that helps users track their fitness goals.</p>
//                 </div>
//               </div>
//               <div className="bg-background rounded-lg shadow-sm overflow-hidden">
//                 <img
//                   src="/placeholder.svg"
//                   width="550"
//                   height="310"
//                   alt="Project 3"
//                   className="w-full h-48 object-cover"
//                 />
//                 <div className="p-4 space-y-2">
//                   <h3 className="text-lg font-semibold">Project 3</h3>
//                   <p className="text-muted-foreground">A web application that helps users manage their finances.</p>
//                 </div>
//               </div>
//             </div>
//           </div>
//         </section>
//         <section id="contact" className="w-full py-12 md:py-24 lg:py-32 bg-muted">
//           <div className="container grid gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
//             <div className="space-y-4">
//               <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Contact Me</div>
//               <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Let's Work Together</h2>
//               <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
//                 I'm always excited to take on new projects and collaborate with talented individuals. Feel free to reach
//                 out to me through the form below or via email.
//               </p>
//               <div className="flex flex-col gap-2 min-[400px]:flex-row">
//                 <Link
//                   href="#"
//                   className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
//                   prefetch={false}
//                 >
//                   Email Me
//                 </Link>
//                 <div className="flex items-center gap-4">
//                   <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
//                     <LinkedinIcon className="h-6 w-6" />
//                   </Link>
//                   <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
//                     <TwitterIcon className="h-6 w-6" />
//                   </Link>
//                   <Link href="#" className="text-muted-foreground hover:underline" prefetch={false}>
//                     <GitlabIcon className="h-6 w-6" />
//                   </Link>
//                 </div>
//               </div>
//             </div>
//             <div className="bg-background rounded-lg shadow-sm p-6">
//               <form className="grid gap-4">
//                 <div className="grid gap-2">
//                   <Label htmlFor="name">Name</Label>
//                   <Input id="name" placeholder="Your name" required />
//                 </div>
//                 <div className="grid gap-2">
//                   <Label htmlFor="email">Email</Label>
//                   <Input id="email" type="email" placeholder="your@email.com" required />
//                 </div>
//                 <div className="grid gap-2">
//                   <Label htmlFor="message">Message</Label>
//                   <Textarea id="message" placeholder="Your message" rows={4} required />
//                 </div>
//                 <Button type="submit" className="w-full">
//                   Send Message
//                 </Button>
//               </form>
//             </div>
//           </div>
//         </section>
//       </main>
//       <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
//         <p className="text-xs text-muted-foreground">&copy; 2024 John Doe. All rights reserved.</p>
//       </footer>
//     </div>
//   )
// }

// function GitlabIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
//     </svg>
//   )
// }


// function LinkedinIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
//       <rect width="4" height="12" x="2" y="9" />
//       <circle cx="4" cy="4" r="2" />
//     </svg>
//   )
// }


// function MountainIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
//     </svg>
//   )
// }


// function TwitterIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
//     </svg>
//   )
// }


// function XIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M18 6 6 18" />
//       <path d="m6 6 12 12" />
//     </svg>
//   )
// }
